### PR TITLE
add hvac python module

### PR DESCRIPTION
**Pull request by sbrile**
adding hvac python module to support hashicorp vault lookup plugin.

### CODE REVIEW

**Comment by sbrile** [comment]
This will fix issue #184

**Comment by austlane** [comment]
The `hashi_vault` lookup plugin is provided by `community.hashi_vault`
> `community.general.hashi_vault` is a simple [redirect](https://github.com/ansible-collections/community.general/blob/6.4.0/meta/runtime.yml#L16-L17) to `community.hashi_vault.hashi_vault`


`community.hashi_vault` specifies it's python requirements properly in [meta/ee-requirements.txt](https://github.com/ansible-collections/community.hashi_vault/blob/4.1.0/meta/ee-requirements.txt)

Thus, the cleaner approach would be to include `community.hashi_vault` in the `_build/requirements.yml` file of the EE.

**Comment by sbrile** [comment]
Only installing the collection wasn't enough for me.  I had to install the hvac module separately.   I also added community.hashi_vault to my collections/requirements.yml in my ansible project repo.  During the project sync, AWX installed the collection, but not the hvac module.

**Comment by sbrile** [comment]
I verified adding community.hashi_vault in the _build/requirements.yml worked in my dev environment.  The docker build must be including some extra smarts to recursively fetch the required python libraries.   I'll close this PR and submit a new one.

**Pull request closed without merging**
