### PR TITLE
Update receptor + ovirt collection

### PR DESCRIPTION
**Pull request by shanemcd**
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/854

### CODE REVIEW

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Review by ryanpetrello — APPROVED** [review]

**Comment by shanemcd** [comment]
recheck

**Pull request merged**
