### PR TITLE
Move ansible-builder files into context folder

### PR DESCRIPTION
**Pull request by pabelanger**
This clean up the top-level directory of the repo, and uses the default
value for context.  I also find it helps to show which files will be
generated by ansible-builder, and should not be manually modified.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by shanemcd** [comment]
I put stuff at the top level because I assume that’s where Brew expects stuff for the downstream builds.

@Spredzy Can you configure this in CPaaS?

**Comment by pabelanger** [comment]
TIL. So, for now I am going to close, then add support to ansible-builder to allow for top-level Dockerfile, while keeping context folder.

**Comment by AlanCoding** [comment]
^ okay, well that's a more refined conclusion than what I came to in

https://github.com/ansible/awx-ee/pull/5#issuecomment-743440819

**Comment by AlanCoding** [comment]
and that's already in a card at https://github.com/ansible/ansible-builder/issues/141

**Pull request closed without merging**
