### PR TITLE
Create tox -ebuild entry point

### PR DESCRIPTION
**Pull request by pabelanger**
This will allow users to quickly 'build' an image locally. By using tox
/ requirements files to manage the ansible-builder dependency.

Signed-off-by: Paul Belanger <pabelanger@redhat.com>

### CODE REVIEW

**Comment by pabelanger** [comment]
WIP for now, I need to add a zuul job, to run tox -ebuild, and ensure git contents don't change.

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 95c3ee3e88d07bee0527df7fffec68131d24cd42

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now a6d015b7f7615288848434375963a1c48d6c6eb5

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 71f11e816500bb20e1104cc84edba4be36b96832

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
