### PR TITLE
Update to use ansible-builder v3

### PR DESCRIPTION
**Pull request by shanemcd**

### CODE REVIEW

**Comment by ziegenberg** [comment]
_Note: Will probably resolve #199._

**Review by ziegenberg — APPROVED** [review]
Seems fine.

**Comment by shanemcd** [comment]
Flipped this back to draft because it's not ready. Rather than baking in a bunch of hacks to get this working, we've decided to slow down and iterate on ansible-builder a bit.

**Comment by ziegenberg** [comment]
@shanemcd sounds reasonable. I'm looking forward to the changes in ansible-builder.

**Comment by ziegenberg** [comment]
Awesome! Thx @shanemcd

**Pull request merged**
