### PR TITLE
Add insights collection

### PR DESCRIPTION
**Pull request by AlanCoding**
Connect https://github.com/ansible/awx-ee/issues/22

### CODE REVIEW

**Comment by AlanCoding** [comment]
From https://github.com/RedHatInsights/ansible-collections-insights/pull/20, we may need to see about re-generating the content with builder, but I think that testinfra probably needs to be excluded anyway, and I ultimately don't expect any changes.

**Comment by AlanCoding** [comment]
Currently attempting to verify with:

```
ansible-builder build -t quay.io/ansible/awx-ee -f execution-environment.yml -c . -container-runtime=podman -v3
```

**Comment by AlanCoding** [comment]
I put up https://github.com/ansible/ansible-builder/pull/230, because we _might_ need that to wrap this work up.

**Comment by AlanCoding** [comment]
Confirmed that re-building does not change any of the Containerfile / requirements

**Review by wenottingham — APPROVED** [review]

**Comment by AlanCoding** [comment]
CI failed due to https://github.com/ansible/awx-ee/pull/67

temporary churn

**Pull request merged**
